#!/bin/bash -e

set -Eeo pipefail

function install_requirements {
  pip install --user -r requirements.txt
}

command="$1"
case "${command}" in
  _unit_tests)
    install_requirements
    python -m unittest discover tests/unit
    ;;
  unit_tests)
    dojo -c Dojofile-py "./tasks _unit_tests"
    ;;
  _integration_tests)
    install_requirements
    python -m unittest discover tests/integration
    ;;
  integration_tests)
    dojo -c Dojofile-py "./tasks _integration_tests"
    ;;
  _functional_tests)
    python -m unittest discover tests/functional
    ;;
  functional_tests)
    dojo -c Dojofile-py "./tasks _functional_tests"
    ;;
  *)
    echo "Invalid command: '${command}'"
    exit 1
    ;;
esac
set +e
